#!/usr/bin/env python
# -*- coding: utf-8 -*-

from petsys import daqd, config
from copy import deepcopy
from time import sleep
import argparse
import os


def get_list(input_list):
        vals = []
        comma_list = input_list.split(',')
        for item in comma_list:
                hyphen_list = item.split('-')
                if len(hyphen_list) > 1:
                        for i in range(int(hyphen_list[0]), int(hyphen_list[1])+1):
                                vals.append(i)
                else:
                        vals.append(float(hyphen_list[0]))
        return vals


parser = argparse.ArgumentParser(description='Acquire data for TDC calibration')
parser.add_argument("--config", type=str, required=True, help="Configuration file")
parser.add_argument("-o", type=str, dest="fileNamePrefix", required=False, help="Data filename (prefix)")
parser.add_argument("--time", type=float, required=True, help="Acquisition time (in seconds)")
parser.add_argument("--enable-hw-trigger", dest="hwTrigger", action="store_true", help="Enable the hardware coincidence filter")
parser.add_argument("--vth1", type=str, dest="vth1", required=True, help="comma separated values for vth1")
parser.add_argument("--vth2", type=str, dest="vth2", required=True, help="comma separated values for vth2")
parser.add_argument("--vthe", type=str, dest="vthe", required=True, help="comma separated values for vthe")
parser.add_argument("--taps", type=str, dest="taps", required=False, help="number of taps [0..6]")
parser.add_argument("--ov", type=str, dest="ov", required=True, help="comma separated values for ov")
parser.add_argument("--bd", type=str, dest="bd", required=True, help="breakdown voltage")
parser.add_argument("--aldo", dest="aldo", action="store_true", help="switch for ALDO usage")
parser.add_argument("--trigger", type=str, dest="trigger", required=False, help="trigger type (none, ext, int)")
parser.add_argument("--freq", type=float, dest="freq", required=False, help="internal trigger frequency (in kHz)")
parser.add_argument("--phase", type=float, dest="phase", required=False, help="trigger phase (in clk)")
parser.add_argument("--prescale", type=int, dest="prescale", required=False, help="external trigger prescale [0..63]")
parser.add_argument("--l1", dest="l1", action="store_true", help="Enable the L1 filtering")
parser.add_argument("--pedestals", dest="pedestals", action="store_true", help="Enable the acquisition of pedestals")
parser.add_argument("--enable-channels", dest="enChannels", required=False, help="comma separated vector of enabled channels")
parser.add_argument("--fix-channels", dest="fixChannels", required=False, help="comma separated vector of channels for which vth1 is fixed at 30")


#------------------------
# parsing input arguments
args = parser.parse_args()

vth1_list = get_list(args.vth1)
vth2_list = get_list(args.vth2)
vthe_list = get_list(args.vthe)
ov_list   = get_list(args.ov)

taps = 6
if args.taps:
        taps = args.taps

if( args.enChannels ):
        args.enChannels = args.enChannels.split(',')
        #print(args.enChannels)

if( args.fixChannels ):
        args.fixChannels = args.fixChannels.split(',')
        #print(args.fixChannels)

if not args.fileNamePrefix:
        with open('/data/tofhir2/last_run') as f:
                run = [int(x) for x in next(f).split()]
                os.remove('/data/tofhir2/last_run')
                with open('/data/tofhir2/last_run','w+') as f:
                        f.write(str(run[0]+1))
        args.fileNamePrefix = "/data/tofhir2/raw/run%04d" % (run[0]+1)

if args.pedestals:
        print("INFO: acquiring pedestals")
        command = "./acquire_qdc_calibration_fixed  --config "+args.config+" -o "+args.fileNamePrefix+"_ped1"
        os.system(command)


#-----------------------------
# load configuration from file
mask = config.LOAD_ALL
# if args.mode != "mixed":
#         mask ^= config.LOAD_QDCMODE_MAP
mask ^= config.LOAD_QDCMODE_MAP
systemConfig = config.ConfigFromFile(args.config, loadMask=mask)

daqd = daqd.Connection()
daqd.initializeSystem()
systemConfig.loadToHardware(daqd, bias_enable=config.APPLY_BIAS_ON)

asicsConfig = daqd.getAsicsConfig()
activeAsics = daqd.getActiveAsics()


#--------------
# trigger modes
if args.trigger == "none":
        print "### self-triggering mode ###"
if args.trigger == "int":
        # Enable INTERNAL triggers from FEB/D to J15
        daqd.write_config_register_tgr(8, 0x21A, 0x81)
        daqd.setTestPulsePLL(100, int(1./(args.freq*6.25e-06)), args.phase, False)
if args.trigger == "ext":
        # Enable EXTERNAL L1 trigger source from J15
        ext_delay = 1917 # Delay added by FPGA in 6.25 ns increments
        daqd.write_config_register_tgr(8, 0x21A, 0x11)
        daqd.write_config_register_tgr(64, 0x02A0, (1<<63) | (0<<62) | (3 << 48) | ( args.prescale << 16) | (ext_delay) ) # prescale: 0..63 -- 0 is 0%, 63 is 63/64%

#--------------------------------------------------------------------
# enable ALDO in case needed (it's only on even ASICs, e.g. 0,2,4...)
if args.aldo:
        hvdac_config = daqd.get_hvdac_config()
        for portID, slaveID, railID in hvdac_config.keys():
                #print portID, slaveID, railID
                hvdac_config[(portID, slaveID, railID)] = systemConfig.mapBiasChannelVoltageToDAC((portID, slaveID, railID), 45)
        daqd.set_hvdac_config(hvdac_config)


#------------------------------------------------
# enable required channels (all if not specified)
for portID, slaveID, chipID in activeAsics:
        ac = asicsConfig[(portID, slaveID, chipID)]
        for channelID in range(32):
                cc = ac.channelConfig[channelID]
                cc.setValue("c_tgr_main", 0b11)

if( args.enChannels ):
        for portID, slaveID, chipID in activeAsics:
                ac = asicsConfig[(portID, slaveID, chipID)]
                for channelID in args.enChannels:
                        cc = ac.channelConfig[int(channelID)]
                        cc.setValue("c_tgr_main", 0b00)

else:
        for portID, slaveID, chipID in activeAsics:
                ac = asicsConfig[(portID, slaveID, chipID)]
                for channelID in range(32):
                        cc = ac.channelConfig[channelID]
                        cc.setValue("c_tgr_main", 0b00)

if args.trigger == "ext":
        for portID, slaveID, chipID in activeAsics:
                if chipID%2 is not 0:
                        continue
                gc = asicsConfig[(portID, slaveID, chipID)].globalConfig
                # Enable L1 trigger for even ASICs (with flex and ALDO)
                if args.l1 :
                        gc.setValue("c_l1_enable", 0b01)
                else:
                        gc.setValue("c_l1_enable", 0b00)
                gc.setValue("c_l1_latency", 484) # Delay expected by ASIC in 25 ns increments
        # Use ASIC 1 channel 0 to timetag the trigger pulses
        asicsConfig[(0, 0, 3)].globalConfig.setValue("c_ext_tp_en", 0b1)
        asicsConfig[(0, 0, 3)].channelConfig[0].setValue("c_tgr_main", 0b01)
        #asicsConfig[(0, 0, 2)].globalConfig.setValue("c_ext_tp_en", 0b1)
        #asicsConfig[(0, 0, 2)].channelConfig[15].setValue("c_tgr_main", 0b01)


asicsConfig0 = deepcopy(asicsConfig)
daqd.openRawAcquisition(args.fileNamePrefix)
cfg = deepcopy(asicsConfig0)


#--------------------------------
# scan on thresholds and / or ov
for vth1 in vth1_list:
        for vth2 in vth2_list:
                for vthe in vthe_list:
                        for ov in ov_list:
                                
                                for portID, slaveID, chipID in activeAsics:
                                        ac = cfg[(portID, slaveID, chipID)]
                                        for channelID in range(32):
                                                cc = ac.channelConfig[int(channelID)]
                                                
                                                #cc.setValue("cfg_a3_vth_t1", vth1)
                                                #cc.setValue("cfg_a3_vth_t2", dac_setting_vth2)
                                                #cc.setValue("cfg_a3_vth_e", dac_setting_vthe)
                                                
                                                dac_setting_vth1 = systemConfig.mapAsicChannelThresholdToDAC((portID, slaveID, chipID, channelID), "vth_t1", int(vth1))
                                                cc.setValue("cfg_a3_vth_t1", dac_setting_vth1)
                                                dac_setting_vth2 = systemConfig.mapAsicChannelThresholdToDAC((portID, slaveID, chipID, channelID), "vth_t2", int(vth2))
                                                cc.setValue("cfg_a3_vth_t2", dac_setting_vth2)
                                                dac_setting_vthe = systemConfig.mapAsicChannelThresholdToDAC((portID, slaveID, chipID, channelID), "vth_e", int(vthe))
                                                cc.setValue("cfg_a3_vth_e", dac_setting_vthe)
                                                #print("%d %d %d %d : %d,%d,%d") % (portID,slaveID,chipID,channelID,dac_setting_vth1,dac_setting_vth2,dac_setting_vthe)
                                                
                                                cc.setValue("cfg_a2_postamp_t_delay",int(taps))
                                                
                                if( args.fixChannels ):
                                        for ac in cfg.values():
                                                for ch in args.fixChannels:
                                                        
                                                        #cc.setValue("cfg_a3_vth_t1", 10)
                                                        #cc.setValue("cfg_a3_vth_t2", 10)
                                                        print "fixing channel %d" % int(ch)
                                                        cc = ac.channelConfig[int(ch)]
                                                        dac_setting_vth1 = systemConfig.mapAsicChannelThresholdToDAC((portID, slaveID, chipID, channelID), "vth_t1", int(15))
                                                        cc.setValue("cfg_a3_vth_t1", dac_setting_vth1)
                                                        dac_setting_vth2 = systemConfig.mapAsicChannelThresholdToDAC((portID, slaveID, chipID, channelID), "vth_t2", int(15))
                                                        cc.setValue("cfg_a3_vth_t2", dac_setting_vth2)
                                
                                if not args.aldo:
                                        biasVoltageConfig = daqd.get_hvdac_config()
                                        for key in daqd.getActiveBiasChannels():
                                                offset, prebd, bd, over__ = systemConfig.getBiasChannelDefaultSettings(key)
                                                vset = offset + bd + float(ov)
                                                dac_setting = systemConfig.mapBiasChannelVoltageToDAC(key, vset)
                                                biasVoltageConfig[key] = dac_setting
                                                daqd.set_hvdac_config(biasVoltageConfig)
                                
                                if args.aldo:
                                        for portID, slaveID, chipID in activeAsics:
                                                if chipID%2 is not 0:
                                                        continue
                                                gc = (cfg[(portID, slaveID, chipID)]).globalConfig
                                                dac_A, dac_B = systemConfig.mapALDOVoltageToDAC((portID, slaveID, chipID),args.bd,float(ov))
                                                gc.setValue("c_aldo_en", 0b11)
                                                gc.setValue("Valdo_A_DAC", dac_A)
                                                gc.setValue("Valdo_B_DAC", dac_B)
                                                
                                #for ext_delay in range(1890, 1920):
				for _ in range(1):
                                        daqd.write_config_register_tgr(64, 0x02A0, (1<<63) | (0 << 62) | (3 << 48) | ( args.prescale << 16) | (ext_delay) ) # prescale: 0..63 -- 0 is 0%, 63 is 63/64%
                                        
                                	daqd.setAsicsConfig(cfg)
		                	sleep(0.1)
		                	print "ov: %3.1f,   vth1: %2d,   vth2: %2d,   vthe: %2d   ext_delay: %d" % (float(ov), int(vth1), int(vth2), int(vthe), ext_delay)
		                	daqd.acquire(args.time, float(ov), 10000*(int(vth1)+1)+100*(int(vth2)+1)+int(vthe)+1)
                                        
systemConfig.loadToHardware(daqd, bias_enable=config.APPLY_BIAS_OFF)
daqd.setTestPulseNone()


if args.pedestals:
        print("INFO: acquiring pedestals")
        command = "./acquire_qdc_calibration_fixed  --config "+args.config+" -o "+args.fileNamePrefix+"_ped2"
        os.system(command)
