#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
import argparse
import bitarray
from petsys import config, tofhir2, bitarray_utils
import json

def main(argv):
	
	parser = argparse.ArgumentParser(description='Build a TOFHiR2 JSON file for DAQv1')
	parser.add_argument("--config", type=str, required=True, help="Configuration file")
	parser.add_argument("-o", type=str, required=True, help="Output file name")

	parser.add_argument("--channel", default=0, type=int, help="Channel ID")
        parser.add_argument("--ith_t1", type=int, dest="ith_t1", required=False, help="vth T1 value")

	args = parser.parse_args()


	# ccLink, ccPort and chipID
	targetAsics = [ (1, 1, 1) ]

	# Allocate  default ASIC configurations
	asicsConfig = {}
	for ccLink, ccPort, chipID in targetAsics:
		asicsConfig[(ccLink, ccPort, chipID)] = tofhir2.AsicConfig()


	# Apply configurations from config.ini
	systemConfig = config.ConfigFromFile(args.config, loadMask=0x0)
	systemConfig.applyConfigToAsics(asicsConfig)


	# Modify the ASIC configurations as needed.
	# Example: For every ASIC, set the thresholds of a channel
	for (ccLink, ccPort, chipID), ac in asicsConfig.items():
		cc = ac.channelConfig[args.channel]

		if args.ith_t1 is not None: cc.setValue("cfg_a3_ith_t1", args.ith_t1)


	## Template code to set ALDO voltage on ASIC (1, 1, 1)
	## Setting to low range, DAC = 200 (make up value)
	#asicsConfig[(1, 1, 1)].globalConfig.setValue("Valdo_A_Gain", 0)
	#asicsConfig[(1, 1, 1)].globalConfig.setValue("Valdo_A_DAC", 200)


	write_json(asicsConfig, args.o)
	return 0

def write_json(asicsConfig, outputFileName):

	outputFile = open(outputFileName, "w")

	targetAsics = asicsConfig.keys()
	targetAsics.sort()


	json_data = []

	for ccLink, ccPort, chipID in targetAsics:
		ac = asicsConfig[(ccLink, ccPort, chipID)]

		json_data.append(make_json_register(ccLink, ccPort, chipID, 32, ac.globalConfig))
		for ch in range(32):
			json_data.append(make_json_register(ccLink, ccPort, chipID, ch, ac.channelConfig[ch]))


	outputFile.write(json.dumps(json_data, sort_keys=True, indent=4))

	outputFile.close()
	return None


chipID_map = {
	}

def make_json_register(ccLink, ccPort, chipID, register_id, cfg_value):
	register_write = True


	register_length = len(cfg_value)
	payload = bitarray.bitarray(256)
	payload.setall(False)
	payload[0:register_length] = cfg_value[0:register_length]
	payload = bytearray(payload.tobytes())

	cmd32 = [0 for n in range(8)]
	for n, v in enumerate(payload):
		idx32 = n/4
		sh32 = n % 4
		sh32 *= 8

		v32 = cmd32[idx32]
		v32 = v32 | (v << sh32)
		cmd32[idx32] = v32




	json_data = []
	json_data.append({
		"CC link" : "%02X" % ccLink,
		"CC port" : "%02X" % ccPort,
		"ChipID" : "%02X" % chipID,
		"R/W mode" : "1",
		"Register address" : "%02X" % register_id,
		"Register length" : "%02X" % register_length

		})

	for idx32, v32 in enumerate(cmd32):
		rev32 = 7 - idx32
		json_data.append({ "dword%d" % rev32 : "%08X" % v32 })


	global_chip_id = (ccLink << 16) | (ccPort << 8) | chipID
	json_data = { "Chip_%08X_reg%02d" % (global_chip_id, register_id) : json_data }

	return json_data







	return  None



if __name__ == '__main__':
	sys.exit(main(sys.argv))
