#!/usr/bin/env python
# -*- coding: utf-8 -*-

from petsys import daqd, config
from copy import deepcopy
import argparse
import struct
import sys

# channel : ( bad ID, bar end )
# bar end:
# 0 for bottom
# 1 for top
# -1 for others (eg, trigger channel)

bar_map = {
	15	: (0, 0),
	13	: (1, 0),
	11	: (2, 0),
	9	: (3, 0),
	7	: (4, 0),
	5	: (5, 0),
	3	: (6, 0),
	1	: (7, 0),
	0	: (8, 0),
	2	: (9, 0),
	4	: (10, 0),
	6	: (11, 0),
	8	: (12, 0),
	10	: (13, 0),
	12	: (14, 0),
	14	: (15, 0),

	16	: (0, 1),
	18	: (1, 1),
	20	: (2, 1),
	22	: (3, 1),
	24	: (4, 1),
	26	: (5, 1),
	28	: (6, 1),
	30	: (7, 1),
	31	: (8, 1),
	29	: (9, 1),
	27	: (10, 1),
	25	: (11, 1),
	23	: (12, 1),
	21	: (13, 1),
	19	: (14, 1),
	17	: (15, 1)
	
	}

def main():
	parser = argparse.ArgumentParser(description='Make a simple channel and trigger map')
	parser.add_argument("-o", type=str, required=True, help="Output file")
	parser.add_argument("--port", type=int, required=True, action="append", help="Port ID")
	parser.add_argument("--slave", type=int, required=True, action="append", help="Slave ID")
	parser.add_argument("--trigger-port", dest="trigger_port", type=str, required=False, action="append", help="File name")
        parser.add_argument("--noTriggerBoard", dest="noTrigger", action="store_true", help="enable only if the system has a DAQ board but no Clock & Trigger board")
	args = parser.parse_args()

	channelOutputFile = open(args.o + "_channel.tsv", "w")
	triggerOutputFile = open(args.o + "_trigger.tsv", "w")


        if not args.noTrigger and args.trigger_port is None:
                print "ERROR: Please enter same number of trigger_port IDs as FEB/Ds in the system"
                exit(1)

        if not args.noTrigger and len(args.trigger_port) != len(args.port):
                print "ERROR: Please enter same number of trigger_port IDs as FEB/Ds in the system"
                exit(1)
        

	region_list = []
	for i in range(len(args.port)):
		portID = int(args.port[i])
		slaveID = int(args.slave[i])
                if args.noTrigger:
                        trigger_port = i 
                else:
                        trigger_port = int(args.trigger_port[i])
		
		for quadrant in range(4):
			trigger_region = 4 * trigger_port + quadrant
			region_list.append(trigger_region)
			for asicID in range(4*quadrant, 4*quadrant + 4):
				for channelID in range(32):
					bar, tb = bar_map[channelID]					
					channelOutputFile.write("%(portID)s\t%(slaveID)d\t%(asicID)d\t%(channelID)d\t%(trigger_region)d\t%(bar)d\t%(tb)d\n" % locals())
					
			triggerOutputFile.write("%(trigger_region)d\t%(trigger_region)d\tM\n" % locals())
					
	for i in range(0, len(region_list)):
		for j in range(i+1, len(region_list)):
			trigger_region1 = region_list[i]
			trigger_region2 = region_list[j]
			if trigger_region1 == trigger_region2: 
				continue
			
			triggerOutputFile.write("%(trigger_region1)d\t%(trigger_region2)d\tC\n" % locals())
	
	channelOutputFile.close()
	triggerOutputFile.close()
		
if __name__ == '__main__':
	main()
