#!/usr/bin/env python
# -*- coding: utf-8 -*-

from petsys import daqd, config
from copy import deepcopy
import argparse
import math
import time


def main():
	parser = argparse.ArgumentParser(description='Set FEM powe ON/OFF')
	parser.add_argument("--power", type=str, required=True, choices=["off", "on"], help="Set FEM power")
	args = parser.parse_args()

	connection = daqd.Connection()
	
	if args.power == "on":
		connection.set_fe_power(True)
	else:
		connection.set_fe_power(False)
	
	

if __name__ == "__main__":
	main()
