#!/usr/bin/env python
# -*- coding: utf-8 -*-

from petsys import daqd, config, spi
from copy import deepcopy
import argparse
import math
import time



def main():
	parser = argparse.ArgumentParser(description='Set UUT power ON/OFF')
	parser.add_argument("--power", type=str, required=True, choices=["off", "on"], help="Set UUT power")
	args = parser.parse_args()

	conn = daqd.Connection()


	if args.power == "on":
		v = 0
		v |= 0b100 # Enable RED LED
		v |= 0b111000 # Enable power
		v |= 0b1111000000 # Enable BV loads
	else:
		v = 0

	spi.spi_reg(conn, 0, 0, 0x10+0, 64, v)

	return 0



if __name__ == "__main__":
	main()

