#!/usr/bin/env python
# -*- coding: utf-8 -*-

from petsys import tester_controller, config, spi
from copy import deepcopy
import argparse
import math
import time



def main():
	parser = argparse.ArgumentParser(description='Set UUT power ON/OFF')
	parser.add_argument("--power", type=str, required=True, choices=["on", "tester_off", "uut_off"], help="Set UUT power")
	args = parser.parse_args()

	conn = tester_controller.Connection()

	if args.power == "on":
		conn.set_fe_power(True)
	elif args.power == "uut_off":
		conn.set_fe_power(False)
	else:
		conn.set_fe_power_all(False)

	return 0



if __name__ == "__main__":
	main()

